### PR TITLE
feat!: support Next 13, drop support for Next 12

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds support for Next 13. It drops support for Next 12 (see **Reasoning for dropping Next 12 support** below).

### `<PrismicNextImage>` changes

- Adds support for Next 13's new `next/image` component with many improvements ([see the official list here](https://nextjs.org/docs/api-reference/next/legacy/image#comparison)).
- Adds a `fallback` prop used to define what is rendered when the given Image field is empty. It defaults to `null`.
- Drops support for Next 12's `next/image` `layout` prop. The new `next/image` component recommends using a combination of CSS, the `width` prop, the `height` prop, and the `fill` prop to style your images.

#### Migration steps

`<PrismicNextImage>` is a light wrapper around `next/image`. All `next/image` props are shared with `<PrismicNextImage>`, except the `src` prop since you use a `field` prop with an Image field instead.

[See Next.js's official migration guide here](https://nextjs.org/docs/advanced-features/codemods#next-image-experimental-experimental)

If you are using the `layout` prop with `<PrismicNextImage>` (which is passed directly to `next/image`), update your images's styling appropriately to support the new `next/image`.

#### Examples

```tsx
<PrismicNextImage field={myImageField} />
<PrismicNextImage field={myImageField} width={400} />
<PrismicNextImage field={myImageField} height={300} />
<PrismicNextImage field={myImageField} width={400} height={300} />

// All `next/image` props are supported.
<PrismicNextImage field={myImageField} fill={true} />
<PrismicNextImage
        field={myImageField}
        sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                33vw"
/>

// A fallback value can be provided.
<PrismicNextImage field={emptyField} fallback={<p>No image given!</p>} />
```

### Reasoning for dropping Next 12 support

1. Next 13 introduces a new `next/image` component which is not API-compatible with Next 12's `next/image` component.
2. Upgrading from Next 12 to Next 13 should be a straightforward upgrade. [See Next.js's official upgrade guide](https://nextjs.org/docs/upgrading).

If you are unable to upgrade your website to Next 13, stay on a previous version of `@prismicio/next` that supports Next 12. We recommend upgrading your project to Next 13 and the latest version of `@prismicio/next` as soon as you are able to.

### Support for Next.js's experimental `app` directory

The `app` directory with React Server Components is not currently supported. Please see this comment for more details: https://github.com/prismicio/prismic-next/pull/48#issuecomment-1316270169

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by angeloashmore** [comment]
Hey @aaron5670 and anyone else seeing this, I will be working on this PR and publishing Next 13 support soon. Thanks for your patience. 🙂

**Comment by angeloashmore** [comment]
Hey everyone, we are currently updating documentation to go along with this release. In the meantime, you can use `@prismicio/next` with Next.js 13 using the latest alpha version:

```sh
npm install @prismicio/next@alpha
```

The full release should be out this week or early next week. 🙂

**Comment by aaron5670** [comment]
Thanks, great work @angeloashmore! 😄

**Comment by frankstallone-klaviyo** [comment]
Does this PR also include updates for use with Next.js 13's new routing system in the `app/` directory? The new `page | layout | loading | error | template | head` special files are an attractive feature.

**Comment by aaron5670** [comment]
> Does this PR also include updates for use with Next.js 13's new routing system in the `app/` directory? The new `page | layout | loading | error | template | head` special files are an attractive feature. 

I"m also interested in this. :)

**Comment by frankstallone-klaviyo** [comment]
@angeloashmore your detailed response here is very much appreciated. Thank you!

I get it. Being in beta, and unstable — makes it difficult to commit your time, effort, and energy towards making this work for now. Although I appreciate the extent in which you detailed workarounds, I would consider this 'bleeding edge' and not production ready. Therefore, I will only hope the `app` directory gets out of beta soon! We'll continue to walk in the direction of using the `pages` directory for now. I am pleased with the cadence the Prismic team is putting towards keeping up with the changing stacks. Makes me more confident in the service. 💪🏻

**Comment by frankstallone-klaviyo** [comment]
"Breaking change (fix or feature that would cause existing functionality to change)" — Wouldn't this be the case since y'all are dropping support for Next.js 12's `next/image`? There are even instructions in this PR for migrating old `next/image` API to the latest. Maybe Next.js 13's `next/image` does not break if you do not migrate?

**Comment by angeloashmore** [comment]
Hey @frankstallone-klaviyo, you're right, this is a breaking change. The checkboxes have been updated.

`<PrismicNextImage>` is a light wrapper around `next/image` that primarily maps a Prismic Image field's URL and dimensions to `next/image`. Thus, API changes to `next/image` bubble up to `<PrismicNextImage>` except for the `src` prop.

Steps for migrating from the legacy `next/image` to the new `next/image` can be found here: https://nextjs.org/docs/advanced-features/codemods#next-image-experimental-experimental

I restructured the "`<PrismicNextImage>` changes" section above to to make that clearer. Hope that helps! 🙂

**Comment by angeloashmore** [comment]
Thanks again to everyone for your patience getting this release out.

This PR has been merged and published as **v1.0.0**. 🎉 `@prismicio/next` now supports Next.js 13 and its new `next/image` component.

## Upgrading

You can upgrade to the latest version with the following command:

```sh
npm install @prismicio/next@latest
```

Your `<PrismicNextImage>` components may need to be adjusted since `next/image` has changed. [See Next.js's official guide to learn how to migrate](https://nextjs.org/docs/advanced-features/codemods#next-image-experimental-experimental).

If you encounter any bugs or have any feature requests, please submit them to this GitHub repository. Thanks!

**Pull request merged**
