### PR TITLE
Nick/test exit preview

### PR DESCRIPTION
**Pull request by dayhaysoos**
This was originally supposed to be for the tests for exitPreview but ended up being a big refactor of previous work.

### Additions

`<PrismicPreview />` component which takes in a `repoName` string which is the name of your Prismic Repo. It wraps around the entire Next project and adds the Prismic Toolbar by doing so.

A `helps.ts` file that makes it easier for a user to set up `createClient`. The main function is `enableClientServerSupport` and is intended to be set up like this:

`prismic.ts`

```js
export const createClient = (
  context: GetStaticPropsContext,
  options: Prismic.ClientConfig = {}
) => {
  const prismicClient = Prismic.createClient(apiEndpoint, options);

  enableClientServerSupport(prismicClient, context);

  return prismicClient;
};
```

And then within `getStaticProps`

```js
export async function getStaticProps(context: GetStaticPropsContext) {
  const client = createClient(context);

  const home = await client.getByUID('page', 'home');

  return {
    props: {
      home,
    },
  };
}
```

### CODE REVIEW

**Comment by angeloashmore** [comment]
## createPreviewEndpoint

Since this file is called within a user's own API function rather than returning its own API function, the name shouldn't have `create` in it. Maybe this could be renamed to `setPrismicPreviewData`?

With that change, the name does not imply that it will also redirect. For that, a separate function could be added called `redirectToPreviewURL`.

A user's `pages/api/preview.ts` file could look like this:

```typescript
import { NextApiRequest, NextApiResponse } from "next";
import * as prismicNext from "prismic-next";

import { linkResolver, createClient } from "../../prismic";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const client = createClient();

  prismicNext.setPreviewData({ req, res });

  await prismicNext.redirectToPreviewURL({ req, res, client, linkResolver });
}
```

The benefit of this style over a single `handlePreviewEndpoint` function is transparency and flexibility. It is clear what the API route is doing:
1. Setting Preview Data for Prismic (`prismicNext.setPreviewData`)
2. Redirecting the the Preview URL (`prismicNext.redirectToPreviewURL`)

If a user wants to do any additional actions between these calls, they can.

`handlePreviewEndpoint` does not say what it does and does not allow user intervention.

**Comment by angeloashmore** [comment]
## exitPreview

This function seems to do two things:
1. Clear the Next.js preview cookie with `res.clearPreviewData()`
2. Redirect the user back to `/`

Redirecting a user back to `/` is undesirable in my opinion. If someone is previewing edits on a page and decides to exit the preview, they should be shown the same page without preview data. This creates a more seamless experience. Something to consider: what happens when someone is previewing an unpublished page? Where should they be redirected to?

As an aside, using the `any` type is discouraged except in very specific situations (such as defining generics). The `.eslint.cjs` file looks empty. Is there a reason for this? The ESLint config from https://github.com/prismicio/prismic-typescript-template includes a rule warning against `any`.

**Comment by angeloashmore** [comment]
## <PrismicPreview>

- Hooks need a clean-up function.
- What if a user names their API preview endpoints something other than `/api/preview` and `/api/exit-preview`?
- What happens if a user's repository requires the legacy toolbar? Is there a way can prompt them to request an upgrade?

**Comment by angeloashmore** [comment]
## index.js

What should the public API of the library be? What is exported? Is there a consistent naming scheme we should use?

This is currently exported from the library:

- createPreviewEndpoint
- exitPreview
- updateNextPreview
- PrismicPreview
- enableClientServerSupport
- getPreviewRefFromContext

Should we exported everything or only export what users will use? Are there any TypeScript types we need to export?

**Comment by dayhaysoos** [comment]
@angeloashmore 

### <PrismicPreview />
I made it so that you can pass update and exit api URLs, they would default to `/api/preview` and `api/exit-preview` though.

I don't know what you mean as far as legacy toolbar, would need to learn more.


### exports

We should definitely only export what the users would use imo, need to revisit this after refactor from other feedback

**Pull request merged**
